### ISSUE TITLE
有的可以下载，有的就报401错误

### ISSUE THREAD

**Issue by CY-Christin** [397179459/Spider-Zhihu#1]
报错信息
Traceback (most recent call last):
  File "zhihuSpider.py", line 210, in <module>
    json_text_tmp = url_question(question_id)
  File "zhihuSpider.py", line 60, in url_question
    return url_json(question_url)
  File "zhihuSpider.py", line 45, in url_json
    response = urllib.request.urlopen(request)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Authorization Required

**Comment by 397179459** [comment]
@ch634421335  ①先用你自己的浏览器进入报401的网址，不要登录用户。②把401网址发出来。

**Comment by CY-Christin** [comment]
1. 不登陆无法查看该回答
2. [网址1](https://www.zhihu.com/question/67553801) [网址2](https://www.zhihu.com/question/22212644)

**Comment by 397179459** [comment]
@ch634421335 你好！我这边测试了一下，因为之前一直没做登录鉴权，所以没考虑这个，这边建议你：

#### 1. 先用浏览器登录并查看该问题，在浏览器按F12找到GET的请求，把请求标头中的cookie值复制下来，（如果这一步你搞不定就百度一下怎么操作）
#### 2. 然后在`url_json` 方法中如下修改：
`myCookie = 'sdbasbduaiusdhashdad'    # 这里填写你上一步的复制的值
request = urllib.request.Request(url=myUrl, headers={"user-agent": ua, "cookie": myCookie })`
### 目前按照这种方法，我这边代码测试时通过的。结果见下。
https://imgtu.com/i/WVIy4g

**Comment by CY-Christin** [comment]
~~cookie有点问题需要问一下~~
已经解决了 非常感谢帮助
